"""samainīta trips datubāze

Revision ID: 16afcdad1671
Revises: 874a3382036c
Create Date: 2022-02-16 11:54:35.821000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16afcdad1671'
down_revision = '874a3382036c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_file', sa.String(length=20), nullable=False))
        batch_op.drop_column('img_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_data', sa.BLOB(), nullable=True))
        batch_op.drop_column('img_file')

    # ### end Alembic commands ###
