""".

Revision ID: 575338f6c6e9
Revises: b8de3d8f43de
Create Date: 2022-02-16 21:05:02.622154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575338f6c6e9'
down_revision = 'b8de3d8f43de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reservation_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('reservation_number')

    # ### end Alembic commands ###
