"""Pievienots image

Revision ID: 874a3382036c
Revises: f6ba7638547c
Create Date: 2022-02-16 11:20:58.379933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874a3382036c'
down_revision = 'f6ba7638547c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_data', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('img_data')

    # ### end Alembic commands ###
