""".

Revision ID: b8de3d8f43de
Revises: 
Create Date: 2022-02-16 21:03:49.819962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8de3d8f43de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('number', sa.String(length=18), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agency'))
    )
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=48), nullable=False),
    sa.Column('abbreviation', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_country'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('country_from', sa.Integer(), nullable=True),
    sa.Column('country_to', sa.Integer(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=280), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('ticket_amount', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('img_file', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], name=op.f('fk_trip_agency_id_agency')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip'))
    )
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(length=30), nullable=False),
    sa.Column('owner_surname', sa.String(length=30), nullable=False),
    sa.Column('country_from', sa.String(length=30), nullable=False),
    sa.Column('country_to', sa.String(length=30), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('onwer_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['onwer_id'], ['user.id'], name=op.f('fk_reservation_onwer_id_user')),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name=op.f('fk_reservation_trip_id_trip')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('trip')
    op.drop_table('user')
    op.drop_table('country')
    op.drop_table('agency')
    # ### end Alembic commands ###
