"""typo fix

Revision ID: fe9529c545ed
Revises: 
Create Date: 2022-02-17 02:33:17.703418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe9529c545ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_reservation_onwer_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reservation_owner_id_user'), 'user', ['owner_id'], ['id'])
        batch_op.drop_column('onwer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onwer_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_reservation_owner_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_reservation_onwer_id_user', 'user', ['onwer_id'], ['id'])
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
